In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
N = 50000

print("Number of records to generate:", N)

Number of records to generate: 50000

In [3]:
priorities = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

categories = [
    "Hardware",
    "Software",
    "Network",
    "Access Management",
    "Email",
    "Security",
    "Database",
    "Application"
]

departments = [
    "IT",
    "Finance",
    "HR",
    "Sales",
    "Marketing",
    "Operations",
    "Customer Support"
]

channels = [
    "Email",
    "Phone",
    "Portal",
    "Chat"
]

statuses = [
    "Resolved",
    "Closed",
    "In Progress",
    "Open",
    "Pending"
]

print("Categories created successfully!")

Categories created successfully!

In [4]:
subcategories = {
    "Hardware": [
        "Laptop",
        "Desktop",
        "Printer",
        "Monitor",
        "Keyboard",
        "Mouse"
    ],
    "Software": [
        "Installation",
        "Application Error",
        "License",
        "Update"
    ],
    "Network": [
        "WiFi",
        "VPN",
        "Internet",
        "LAN"
    ],
    "Access Management": [
        "Password Reset",
        "Account Lock",
        "Access Request",
        "Permission Issue"
    ],
    "Email": [
        "Outlook",
        "Mailbox",
        "Spam",
        "Email Access"
    ],
    "Security": [
        "Malware",
        "Phishing",
        "Security Alert",
        "Endpoint Security"
    ],
    "Database": [
        "Connection",
        "Performance",
        "Access",
        "Query Error"
    ],
    "Application": [
        "Application Crash",
        "Login Issue",
        "Performance",
        "Functional Issue"
    ]
}

print("Subcategories created successfully!")

Subcategories created successfully!

In [5]:
agents = [
    "Rahul Sharma",
    "Priya Reddy",
    "Arjun Kumar",
    "Sneha Patel",
    "Vikram Singh",
    "Ananya Rao",
    "Kiran Kumar",
    "Pooja Sharma",
    "Rohit Verma",
    "Neha Reddy",
    "Amit Das",
    "Divya Nair",
    "Sanjay Rao",
    "Meena Patel",
    "Nikhil Kumar"
]

print("Number of agents:", len(agents))

Number of agents: 15

In [6]:
np.random.seed(42)
random.seed(42)

ticket_ids = np.arange(1, N + 1)

priority_data = np.random.choice(
    priorities,
    size=N,
    p=[0.30, 0.45, 0.20, 0.05]
)

category_data = np.random.choice(
    categories,
    size=N,
    p=[0.15, 0.20, 0.18, 0.12, 0.10, 0.08, 0.07, 0.10]
)

department_data = np.random.choice(
    departments,
    size=N
)

channel_data = np.random.choice(
    channels,
    size=N,
    p=[0.30, 0.25, 0.30, 0.15]
)

status_data = np.random.choice(
    statuses,
    size=N,
    p=[0.45, 0.20, 0.15, 0.10, 0.10]
)

agent_data = np.random.choice(
    agents,
    size=N
)

print("Basic ticket data generated successfully!")

Basic ticket data generated successfully!

In [7]:
start_date = pd.Timestamp("2024-01-01")
end_date = pd.Timestamp("2025-12-31")

date_range_days = (end_date - start_date).days

created_dates = [
    start_date + pd.Timedelta(
        days=random.randint(0, date_range_days),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59)
    )
    for _ in range(N)
]

created_dates = pd.to_datetime(created_dates)

print("Created dates generated successfully!")
print("Minimum date:", created_dates.min())
print("Maximum date:", created_dates.max())

Created dates generated successfully!
Minimum date: 2024-01-01 00:10:00
Maximum date: 2025-12-31 23:33:00

In [8]:
sla_targets = {
    "Critical": 4,
    "High": 8,
    "Medium": 24,
    "Low": 48
}

sla_target_data = np.array([
    sla_targets[p]
    for p in priority_data
])

print("SLA targets generated successfully!")

SLA targets generated successfully!

In [9]:
resolution_time_data = []

for priority in priority_data:
    if priority == "Critical":
        hours = np.random.uniform(1, 8)
    elif priority == "High":
        hours = np.random.uniform(2, 16)
    elif priority == "Medium":
        hours = np.random.uniform(4, 40)
    else:
        hours = np.random.uniform(6, 72)

    resolution_time_data.append(round(hours, 2))

resolution_time_data = np.array(resolution_time_data)

print("Resolution times generated successfully!")
print("Minimum:", resolution_time_data.min(), "hours")
print("Maximum:", resolution_time_data.max(), "hours")

Resolution times generated successfully!
Minimum: 1.0 hours
Maximum: 71.99 hours

In [10]:
resolved_dates = []

for created, status, resolution_hours in zip(
    created_dates,
    status_data,
    resolution_time_data
):
    if status in ["Resolved", "Closed"]:
        resolved_dates.append(
            created + pd.Timedelta(hours=float(resolution_hours))
        )
    else:
        resolved_dates.append(pd.NaT)

resolved_dates = pd.to_datetime(resolved_dates)

print("Resolved dates generated successfully!")

Resolved dates generated successfully!

In [11]:
sla_status_data = []

for resolution, target, status in zip(
    resolution_time_data,
    sla_target_data,
    status_data
):
    if status not in ["Resolved", "Closed"]:
        sla_status_data.append("Pending")
    elif resolution <= target:
        sla_status_data.append("Met")
    else:
        sla_status_data.append("Breached")

print("SLA status generated successfully!")

SLA status generated successfully!

In [12]:
satisfaction_data = []

for status, sla_status in zip(status_data, sla_status_data):
    if status in ["Open", "Pending", "In Progress"]:
        satisfaction_data.append(np.nan)
    elif sla_status == "Met":
        satisfaction_data.append(
            round(np.random.uniform(3.5, 5.0), 2)
        )
    else:
        satisfaction_data.append(
            round(np.random.uniform(1.0, 3.5), 2)
        )

satisfaction_data = np.array(satisfaction_data)

print("Customer satisfaction scores generated successfully!")

Customer satisfaction scores generated successfully!

In [13]:
df = pd.DataFrame({
    "Ticket_ID": ticket_ids,
    "Created_Date": created_dates,
    "Resolved_Date": resolved_dates,
    "Priority": priority_data,
    "Category": category_data,
    "Subcategory": [
        random.choice(subcategories[category])
        for category in category_data
    ],
    "Department": department_data,
    "Assigned_Agent": agent_data,
    "Channel": channel_data,
    "Status": status_data,
    "SLA_Target_Hours": sla_target_data,
    "Resolution_Time_Hours": resolution_time_data,
    "SLA_Status": sla_status_data,
    "Customer_Satisfaction": satisfaction_data
})

print("DataFrame created successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

DataFrame created successfully!
Rows: 50000
Columns: 14

In [14]:
df.head(10)

,Ticket_ID,Created_Date,Resolved_Date,Priority,Category,Subcategory,Department,Assigned_Agent,Channel,Status,SLA_Target_Hours,Resolution_Time_Hours,SLA_Status,Customer_Satisfaction
0,1,2025-10-16 03:01:00,2025-10-16 11:11:48,Medium,Database,Performance,Finance,Vikram Singh,Chat,Closed,24,8.18,Met,4.18
1,2,2024-10-08 07:14:00,2024-10-08 13:48:12,Critical,Network,Internet,Operations,Rahul Sharma,Phone,Resolved,4,6.57,Breached,1.29
2,3,2024-05-22 23:06:00,NaT,Medium,Software,Update,Customer Support,Sneha Patel,Email,Open,24,9.46,Pending,NaN
3,4,2025-11-23 23:57:00,2025-11-24 19:29:24,Medium,Email,Email Access,IT,Nikhil Kumar,Phone,Closed,24,19.54,Met,3.54
4,5,2025-07-12 02:37:00,2025-07-14 13:40:00,Low,Network,LAN,IT,Rahul Sharma,Phone,Closed,48,59.05,Breached,1.18
5,6,2025-03-08 01:01:00,2025-03-10 06:13:00,Low,Access Management,Account Lock,Operations,Ananya Rao,Email,Closed,48,53.20,Breached,1.72
6,7,2024-04-05 06:14:00,NaT,Low,Hardware,Mouse,Operations,Neha Reddy,Email,Pending,48,29.76,Pending,NaN
7,8,2025-06-01 19:01:00,NaT,High,Access Management,Access Request,Customer Support,Ananya Rao,Phone,Open,8,3.04,Pending,NaN
8,9,2025-07-28 06:45:00,NaT,Medium,Network,LAN,Operations,Divya Nair,Chat,Pending,24,11.35,Pending,NaN
9,10,2025-10-27 22:34:00,2025-10-28 17:26:12,Medium,Software,Application Error,Operations,Amit Das,Chat,Resolved,24,18.87,Met,4.92

In [15]:
print("Dataset shape:", df.shape)

Dataset shape: (50000, 14)

In [16]:
df.isnull().sum()

Ticket_ID                    0
Created_Date                 0
Resolved_Date            17472
Priority                     0
Category                     0
Subcategory                  0
Department                   0
Assigned_Agent               0
Channel                      0
Status                       0
SLA_Target_Hours             0
Resolution_Time_Hours        0
SLA_Status                   0
Customer_Satisfaction    17472
dtype: int64

In [17]:
print("Duplicate Ticket IDs:", df["Ticket_ID"].duplicated().sum())

Duplicate Ticket IDs: 0

In [18]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              50000 non-null  int64
 1   Created_Date           50000 non-null  datetime64[ns]
 2   Resolved_Date          32528 non-null  datetime64[ns]
 3   Priority               50000 non-null  object
 4   Category               50000 non-null  object
 5   Subcategory            50000 non-null  object
 6   Department             50000 non-null  object
 7   Assigned_Agent         50000 non-null  object
 8   Channel                50000 non-null  object
 9   Status                 50000 non-null  object
 10  SLA_Target_Hours       50000 non-null  int64
 11  Resolution_Time_Hours  50000 non-null  float64
 12  SLA_Status             50000 non-null  object
 13  Customer_Satisfaction  32528 non-null  float64
dtypes: datetime64[ns](2), float64(2), int64(2), object(8)
memory usage: 5.3+ MB

In [20]:
print("Priorities:")
print(df["Priority"].value_counts())

print("\nStatuses:")
print(df["Status"].value_counts())

print("\nSLA Status:")
print(df["SLA_Status"].value_counts())

Priorities:
Priority
Medium      22532
Low         15059
High         9939
Critical     2470
Name: count, dtype: int64

Statuses:
Status
Resolved       22588
Closed          9940
In Progress     7608
Pending         4938
Open            4926
Name: count, dtype: int64

SLA Status:
SLA_Status
Met         17739
Pending     17472
Breached    14789
Name: count, dtype: int64

In [21]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Ticket_ID,50000.0,NaN,NaN,NaN,25000.5,1.0,12500.75,25000.5,37500.25,50000.0,14433.901067
Created_Date,50000,NaN,NaN,NaN,2025-01-01 21:55:20.686799872,2024-01-01 00:10:00,2024-07-01 13:33:45,2025-01-03 05:17:30,2025-07-05 09:12:00,2025-12-31 23:33:00,NaN
Resolved_Date,32528,NaN,NaN,NaN,2025-01-03 15:48:48.694662912,2024-01-01 05:58:36,2024-07-03 09:16:00,2025-01-05 17:20:24,2025-07-07 01:29:45,2026-01-03 18:19:36,NaN
Priority,50000,4,Medium,22532,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,50000,8,Software,10075,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Subcategory,50000,33,Application Error,2553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Department,50000,7,Finance,7281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Assigned_Agent,50000,15,Kiran Kumar,3401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Channel,50000,4,Portal,15057,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Status,50000,5,Resolved,22588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SLA_Target_Hours,50000.0,NaN,NaN,NaN,27.05984,4.0,24.0,24.0,48.0,48.0,15.322188
Resolution_Time_Hours,50000.0,NaN,NaN,NaN,23.668529,1.0,9.82,19.22,33.9,71.99,17.130479
SLA_Status,50000,3,Met,17739,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Satisfaction,32528.0,NaN,NaN,NaN,3.340796,1.0,2.37,3.63,4.31,5.0,1.151512

In [25]:
df.head(10)

,Ticket_ID,Created_Date,Resolved_Date,Priority,Category,Subcategory,Department,Assigned_Agent,Channel,Status,SLA_Target_Hours,Resolution_Time_Hours,SLA_Status,Customer_Satisfaction
0,1,2025-10-16 03:01:00,2025-10-16 11:11:48,Medium,Database,Performance,Finance,Vikram Singh,Chat,Closed,24,8.18,Met,4.18
1,2,2024-10-08 07:14:00,2024-10-08 13:48:12,Critical,Network,Internet,Operations,Rahul Sharma,Phone,Resolved,4,6.57,Breached,1.29
2,3,2024-05-22 23:06:00,NaT,Medium,Software,Update,Customer Support,Sneha Patel,Email,Open,24,9.46,Pending,NaN
3,4,2025-11-23 23:57:00,2025-11-24 19:29:24,Medium,Email,Email Access,IT,Nikhil Kumar,Phone,Closed,24,19.54,Met,3.54
4,5,2025-07-12 02:37:00,2025-07-14 13:40:00,Low,Network,LAN,IT,Rahul Sharma,Phone,Closed,48,59.05,Breached,1.18
5,6,2025-03-08 01:01:00,2025-03-10 06:13:00,Low,Access Management,Account Lock,Operations,Ananya Rao,Email,Closed,48,53.20,Breached,1.72
6,7,2024-04-05 06:14:00,NaT,Low,Hardware,Mouse,Operations,Neha Reddy,Email,Pending,48,29.76,Pending,NaN
7,8,2025-06-01 19:01:00,NaT,High,Access Management,Access Request,Customer Support,Ananya Rao,Phone,Open,8,3.04,Pending,NaN
8,9,2025-07-28 06:45:00,NaT,Medium,Network,LAN,Operations,Divya Nair,Chat,Pending,24,11.35,Pending,NaN
9,10,2025-10-27 22:34:00,2025-10-28 17:26:12,Medium,Software,Application Error,Operations,Amit Das,Chat,Resolved,24,18.87,Met,4.92

In [26]:
df.tail(10)

,Ticket_ID,Created_Date,Resolved_Date,Priority,Category,Subcategory,Department,Assigned_Agent,Channel,Status,SLA_Target_Hours,Resolution_Time_Hours,SLA_Status,Customer_Satisfaction
49990,49991,2024-09-01 18:50:00,2024-09-03 08:48:48,Medium,Security,Phishing,Sales,Pooja Sharma,Chat,Resolved,24,37.98,Breached,1.15
49991,49992,2025-08-28 13:37:00,NaT,Medium,Hardware,Monitor,IT,Rahul Sharma,Chat,Open,24,33.20,Pending,NaN
49992,49993,2024-06-09 20:31:00,NaT,Medium,Application,Functional Issue,Sales,Rohit Verma,Portal,Pending,24,29.67,Pending,NaN
49993,49994,2024-05-01 14:27:00,2024-05-02 18:14:24,Low,Network,LAN,IT,Sneha Patel,Email,Resolved,48,27.79,Met,3.92
49994,49995,2025-08-15 06:16:00,NaT,Medium,Database,Access,Customer Support,Vikram Singh,Portal,Open,24,29.12,Pending,NaN
49995,49996,2024-08-10 03:56:00,2024-08-10 18:25:24,Medium,Security,Phishing,Customer Support,Nikhil Kumar,Chat,Closed,24,14.49,Met,4.07
49996,49997,2025-05-04 11:09:00,NaT,Low,Security,Endpoint Security,Marketing,Sanjay Rao,Chat,Open,48,64.47,Pending,NaN
49997,49998,2024-08-18 01:12:00,2024-08-18 20:25:12,Medium,Email,Spam,Sales,Ananya Rao,Email,Resolved,24,19.22,Met,3.91
49998,49999,2025-01-14 21:09:00,NaT,Medium,Network,Internet,Operations,Pooja Sharma,Email,Open,24,17.99,Pending,NaN
49999,50000,2025-03-02 22:00:00,2025-03-03 08:27:00,High,Network,VPN,Sales,Pooja Sharma,Portal,Closed,8,10.45,Breached,2.45

In [27]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate Ticket IDs:", df["Ticket_ID"].duplicated().sum())

Rows: 50000
Columns: 14
Duplicate rows: 0
Duplicate Ticket IDs: 0

In [28]:
file_path = "IT_ServiceDesk_50000.csv"

df.to_csv(
    file_path,
    index=False
)

print("CSV saved successfully!")
print("File:", file_path)

CSV saved successfully!
File: IT_ServiceDesk_50000.csv

In [29]:
df_check = pd.read_csv(
    "IT_ServiceDesk_50000.csv"
)

print("Rows:", df_check.shape[0])
print("Columns:", df_check.shape[1])

Rows: 50000
Columns: 14

In [30]:
df_check.head()

,Ticket_ID,Created_Date,Resolved_Date,Priority,Category,Subcategory,Department,Assigned_Agent,Channel,Status,SLA_Target_Hours,Resolution_Time_Hours,SLA_Status,Customer_Satisfaction
0,1,2025-10-16 03:01:00,2025-10-16 11:11:48.000000000,Medium,Database,Performance,Finance,Vikram Singh,Chat,Closed,24,8.18,Met,4.18
1,2,2024-10-08 07:14:00,2024-10-08 13:48:12.000000000,Critical,Network,Internet,Operations,Rahul Sharma,Phone,Resolved,4,6.57,Breached,1.29
2,3,2024-05-22 23:06:00,NaN,Medium,Software,Update,Customer Support,Sneha Patel,Email,Open,24,9.46,Pending,NaN
3,4,2025-11-23 23:57:00,2025-11-24 19:29:24.000000000,Medium,Email,Email Access,IT,Nikhil Kumar,Phone,Closed,24,19.54,Met,3.54
4,5,2025-07-12 02:37:00,2025-07-14 13:40:00.000000000,Low,Network,LAN,IT,Rahul Sharma,Phone,Closed,48,59.05,Breached,1.18

In [31]:
import os

file_size_mb = os.path.getsize("IT_ServiceDesk_50000.csv") / (1024 * 1024)

print(f"CSV file size: {file_size_mb:.2f} MB")

CSV file size: 6.02 MB